### PR TITLE
Remove unnecessary flushing var

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by ronag** [comment]
Re-run CI?

**Comment by jsumners** [comment]
> Re-run CI?

Failed again.

**Comment by ronag** [comment]
weird

**Comment by ronag** [comment]
seems to fail on node 12

**Comment by mcollina** [comment]
it seems this is breaking in some subtle way.

**Comment by mcollina** [comment]
Closing for no activity

**Pull request closed without merging**
